### ISSUE TITLE
Translator not working

### ISSUE THREAD

**Issue by arnavvaryani** [gabrielpacheco23/google-translator#21]
Hey, the translator is not working in the example repo

**Comment by DangKhoi1811** [comment]
The same as me, it always return code 429

**Comment by raphaeldelio** [comment]
Please, provide more details. The issue seems to have been solved. 

However, Google has disabled Google Translate in parts of China, as this article states: https://techcrunch.com/2022/09/30/google-appears-to-have-disabled-google-translate-in-parts-of-china/

Therefore, an error 404 is received when trying to hit "translate.google.cn".

I'll replace the URL "translate.google.cn" with "translate.google.com.hk" to exemplify how the default base URL can be replaced in the example repo.
