### ISSUE TITLE
sometimes not working for translation

### ISSUE THREAD

**Issue by ze9786** [gabrielpacheco23/google-translator#38]
Some words can be translated to the target language(for me, chinese and korean), but some words cannot be translated and return the same text as my input.
Below is my code to translate from auto to my target language:
`  var trans = await GoogleTranslator().translate(word, to: myLang);
`
For instance, i want to translate the word "San Francisco" to traditional chinese, after calling the code above, it still return "San Francisco". However, when I go Google Translate website to translate this word, it will return the correct text to me. [see the link](https://translate.google.com/?sl=auto&tl=zh-TW&text=San%20Francisco&op=translate)

**Comment by gabrielpacheco23** [comment]
That's because this package uses the old Google Translate API which is free. Probably the Google Translate website uses the Cloud API which is paid and more accurate about the translations. I'll take a look about the possibility to implement a better translation API client in this package, but for now that's how it works.
